---
name: Integration2
about: Propose a new integration2
title: "[INTEGRATION]"
labels: integration
assignees: ''
body:
  - type: markdown
    attributes:
    value: Thank you for your interest in OpenLineage. We are very interested in new integrations that make it easier for users to adopt the standard. This form will help us collect a bit of information about the integration you are proposing.
  - type: textarea
    attributes:
      label: Integration Target
      description: What are you proposing a new integration with?
      placeholder: i.e. which framework, project, or product

