---
name: Integration
description: Propose a new integration
title: "[INTEGRATION] "
labels: ["integration"]
body:
  - type: markdown
    attributes:
    value: Thank you for your interest in OpenLineage. We are very interested in new integrations that make it easier for users to adopt the standard. This form will help us collect a bit of information about the integration you are proposing.
  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature
  - type: textarea
    attributes:
      label: Use case/motivation
      description: What would you like to happen?
      placeholder: >
          Rather than telling us how you might implement this feature, try to take a
          step back and describe what you are trying to achieve.
  - type: textarea
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the feature.
        Airflow is a community-managed project and we love to bring new contributors in.
        Find us in #airflow-how-to-pr on Slack!
      options:
        - label: Yes I am willing to submit a PR!
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: >
            I agree to follow this project's
            [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"