---
name: Integration
description: Propose a new integration
title: "[INTEGRATION] "
labels: ["integration"]
body:
  - type: markdown
    attributes:
    value: Thank you for your interest in OpenLineage. We are very interested in new integrations that make it easier for users to adopt the standard. This form will help us collect a bit of information about the integration you are proposing.
